name: shapes
version: 1.0.0
description: >-
  Demonstrating inheritance with Dart
author: Peter Loos <peter.loos@gmx.de>
homepage: http://peterloos.de
dependencies:
  sprintf: "^4.0.0"
environment:
  sdk: '>=2.2.0 <3.0.0'
